version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - firelessdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  web:
    build: .
    volumes:
      - .:/var/www/fireless
    ports:
      - '80:3000'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db


volumes:
  firelessdata: